services:
  api:
    ports:
      - '3000:3000'
      - '9229:9229' # Puerto para el Debugger
    volumes:
      - ../../apps/backend:/app
      - /app/node_modules # Preserva los node_modules del contenedor
    command: node --watch --inspect=0.0.0.0:9229 src/server.js

  frontend:
    volumes:
      - ../../apps/frontend:/app
      - /app/node_modules # Preserva los node_modules del contenedor
